### ISSUE TITLE
Issue with vector representation

### ISSUE THREAD

**Issue by praneet195** [wolverinn/HEVC-CU-depths-prediction-CNN#4]
Hi,

Are the vectors depicting 4x4 blocks in the 16x16 matrix from Left to right, top to bottom?
Also, can you please provide example text files that you used in your pipeline that was read by the HM encoder.

**Comment by wolverinn** [comment]
1. yes
2. maybe you can find examples from my other repository: https://github.com/wolverinn/HEVC-CU-depths-dataset

**Comment by praneet195** [comment]
thanks i'll try looking into this
